import Head from 'next/head';
import { Fragment } from 'react';
import { PageLayout } from '../components/PageLayout';
import { Title } from '../components/Title';

function AddIncomePage() {
	return (
		<Fragment>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<PageLayout>
				<Title title={'Add incomes'} />
				<main>todo</main>
			</PageLayout>
		</Fragment>
	);
}

export default AddIncomePage;
