import Head from 'next/head';
import { Fragment } from 'react';
import { ExpenseForm } from '../components/ExpenseForm';
import { PageLayout } from '../components/PageLayout';
import { Title } from '../components/Title';

function AddExpensePage() {
	return (
		<Fragment>
			<Head>
				<title>Budget Sheets App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<PageLayout>
				<Title title={'Add expense'} />
				<ExpenseForm />
			</PageLayout>
		</Fragment>
	);
}

export default AddExpensePage;
