import Head from 'next/head';
import { Fragment } from 'react';
import { PageLayout } from '../components/PageLayout';
import { Title } from '../components/Title';

function StatsPage() {
	// const { isLoading, isError, data, error } = useQuery('filteredExpenses', () =>
	// 	getFilteredExpenses({ filter: 'createdAt', value: '2021-05' })
	// );

	// const content = isLoading ? (
	// 	<p>Loading...</p>
	// ) : (
	// 	data.map((expense) => <p>{expense.createdAt}</p>)
	// );

	return (
		<Fragment>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<PageLayout>
				<Title title={'Stats'} />
				<main>todo</main>
			</PageLayout>
		</Fragment>
	);
}

export default StatsPage;
